version: '3'

services:
  db:
    image: postgres:11.9
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USR=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/:/var/lib/postgresql/data

  web:
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
